spring:
    datasource:
       url: jdbc:mysql://localhost:3306/compras?useSSL=false
       username: root
       password: admin
       driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: default
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
              strategy: org.hibernate.cfg.ImprovedNamingStrategy        
        properties: 
            hibernate: 
              dialect: org.hibernate.dialect.MySQL5Dialect
        
    thymeleaf:
       cache: false
server:
    port: 9099
    
